### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by Luke-Nukem**
Update the link for SDL2_gfx-1.0.1.tar.gz - Internode are usually quite good.

### CODE REVIEW

**Comment by andelf** [comment]
travis-ci fails.

maybe you should add ``./autogen.sh`` to its build command. 

waiting for your fix. :)

**Comment by Luke-Nukem** [comment]
Doh! Don't know why I never checked Travis. Build passing now, also updated the installed SDL2 to 2.0.5.

**Comment by Luke-Nukem** [comment]
Good to go 😸

**Comment by andelf** [comment]
👍

**Pull request merged**
